# Generated by Django 2.2.15 on 2020-08-06 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.TextField(blank=True, null=True)),
                ('proposal_short', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Proposals',
            },
        ),
        migrations.CreateModel(
            name='Pulsars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jname', models.TextField(blank=True, db_column='Jname', null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('gc', models.IntegerField(blank=True, db_column='GC', null=True)),
                ('relbin', models.IntegerField(blank=True, db_column='RelBin', null=True)),
                ('tpa', models.IntegerField(blank=True, db_column='TPA', null=True)),
                ('pta', models.IntegerField(blank=True, db_column='PTA', null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Pulsars',
            },
        ),
        migrations.CreateModel(
            name='Utcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc', models.TextField(blank=True, null=True)),
                ('utc_ts', models.DateTimeField()),
                ('annotation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UTCs',
            },
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beam', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('bw', models.FloatField(blank=True, null=True)),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('rm_pipe', models.FloatField(blank=True, db_column='RM_pipe', null=True)),
                ('dm_pipe', models.FloatField(blank=True, db_column='DM_pipe', null=True)),
                ('dm_fold', models.FloatField(blank=True, db_column='DM_fold', null=True)),
                ('nchan', models.IntegerField(blank=True, null=True)),
                ('nbin', models.IntegerField(blank=True, null=True)),
                ('mjd', models.TextField(blank=True, db_column='MJD', null=True)),
                ('mjd_int', models.IntegerField(blank=True, db_column='MJD_INT', null=True)),
                ('mjd_frac', models.TextField(blank=True, db_column='MJD_frac', null=True)),
                ('pa', models.FloatField(blank=True, db_column='PA', null=True)),
                ('ra', models.TextField(blank=True, db_column='RA', null=True)),
                ('dec', models.TextField(blank=True, db_column='DEC', null=True)),
                ('observer', models.TextField(blank=True, null=True)),
                ('snr_pipe', models.FloatField(blank=True, db_column='SNR_pipe', null=True)),
                ('snr_spip', models.FloatField(blank=True, db_column='SNR_spip', null=True)),
                ('nant', models.IntegerField(blank=True, null=True)),
                ('nant_eff', models.IntegerField(blank=True, null=True)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.Proposals')),
                ('pulsar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.Pulsars')),
                ('utc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.Utcs')),
            ],
            options={
                'db_table': 'Observations',
                'unique_together': {('pulsar', 'utc', 'beam')},
            },
        ),
        migrations.CreateModel(
            name='Searchmode',
            fields=[
                ('pulsar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dataportal.Pulsars')),
                ('beam', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('tsamp', models.FloatField(blank=True, null=True)),
                ('bw', models.FloatField(blank=True, null=True)),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('nchan', models.IntegerField(blank=True, null=True)),
                ('nbit', models.IntegerField(blank=True, null=True)),
                ('npol', models.IntegerField(blank=True, null=True)),
                ('nant', models.IntegerField(blank=True, null=True)),
                ('nant_eff', models.IntegerField(blank=True, null=True)),
                ('dm', models.FloatField(blank=True, db_column='DM', null=True)),
                ('ra', models.TextField(blank=True, db_column='RA', null=True)),
                ('dec', models.TextField(blank=True, db_column='DEC', null=True)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.Proposals')),
                ('utc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.Utcs')),
            ],
            options={
                'db_table': 'Searchmode',
                'unique_together': {('pulsar', 'utc', 'beam')},
            },
        ),
    ]
