# Generated by Django 2.2.15 on 2020-08-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxcal',
            name='bw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fluxcal',
            name='frequency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fluxcal',
            name='nant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fluxcal',
            name='nant_eff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fluxcal',
            name='nbin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fluxcal',
            name='nchan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
