# Generated by Django 2.2.16 on 2020-09-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0002_auto_20200825_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulsars',
            name='gc',
        ),
        migrations.RemoveField(
            model_name='pulsars',
            name='pta',
        ),
        migrations.RemoveField(
            model_name='pulsars',
            name='relbin',
        ),
        migrations.RemoveField(
            model_name='pulsars',
            name='tpa',
        ),
        migrations.RemoveField(
            model_name='utcs',
            name='utc',
        ),
        migrations.CreateModel(
            name='Ephemerides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField()),
                ('ephemeris', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('pulsar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.Pulsars')),
            ],
            options={
                'db_table': 'Ephemerides',
            },
        ),
        migrations.AddField(
            model_name='pulsars',
            name='ephemeris',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataportal.Ephemerides'),
        ),
    ]
