# Generated by Django 2.2.17 on 2021-04-13 02:55

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0004_auto_20210407_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebandings',
            name='processing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.Processings'),
        ),
        migrations.AlterField(
            model_name='ephemerides',
            name='ephemeris',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='targets',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='foldings',
            constraint=models.UniqueConstraint(fields=('processing',), name='unique folding'),
        ),
        migrations.AddConstraint(
            model_name='pipelineimages',
            constraint=models.UniqueConstraint(fields=('processing', 'image_type'), name='unique image type for a processing'),
        ),
        migrations.AddConstraint(
            model_name='pipelines',
            constraint=models.UniqueConstraint(fields=('name', 'revision'), name='unique pipeline'),
        ),
        migrations.AddConstraint(
            model_name='processings',
            constraint=models.UniqueConstraint(fields=('observation', 'pipeline', 'location', 'parent'), name='unique processing'),
        ),
        migrations.AddConstraint(
            model_name='targets',
            constraint=models.UniqueConstraint(fields=('name', 'raj', 'decj'), name='unique target'),
        ),
    ]
