repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
        args: ['--allow-multiple-documents']
-   repo: local
    hooks:
    -   id: helm-chart-version-check
        name: Helm Chart Version Check
        entry: scripts/helm-chart-version-check
        args:
         - kubernetes/meertime-dataportal
         - gwcloud
         - meertime-dataportal
        language: script
        types: [file]
