version: "3"

services:
  mysql:
    image: mysql:8.0.3
    container_name: meertime-mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD
#      - POSTGRES_DATABASE
#      - POSTGRES_USER
#      - POSTGRES_PASSWORD
    env_file:
      - backend/.env
    volumes:
#      - mysql-persistent-storage:/var/lib/mysql
      - ~/docker_mysql:/var/lib/mysql
# to create the db from a dump inside a docker container
      - ~/dumps/meertime_backup.sql:/docker-entrypoint-initdb.d/data.sql
  django:
    image: nexus.gwdc.org.au/meertime/django:2.6
    container_name: meertime_django
    depends_on:
      - mysql
#    environment:
#      - POSTGRES_DATABASE
#      - POSTGRES_USER
#      - POSTGRES_PASSWORD
#      - DB_HOST=mysql
#      - MYSQL_PORT
#      - DJANGO_SECRET_KEY
#      - DEBUG
#      - DEVELOPMENT_MODE
    env_file:
      - backend/.env
    volumes:
      - ./src/static:/static
      - ./backend/media:/media
      - ~/meertime_docker_logs/django:/var/log/django
    command: >
      bash -c "python manage.py collectstatic --noinput
      && gunicorn --bind=0.0.0.0:8000 meertime.wsgi:application"
  react:
    image: nexus.gwdc.org.au/meertime/react:2.7
    container_name: meertime_react
    ports:
      - "3000:3000"
  nginx:
    image: nexus.gwdc.org.au/meertime/nginx:1.3
    ports:
      - "8000:80"
    container_name: meertime_nginx
    depends_on:
      - django
    volumes:
      - ./nginx:/etc/nginx/conf.d
volumes:
  mysql-persistent-storage:
