version: "3"

services:
  postgres:
    image: postgres:14.9
    container_name: meertime-postgres
    env_file:
      - backend/.env
    volumes:
      - ~/docker_postgres:/var/lib/postgresql/data
      # to create the db from a dump inside a docker container
      - ~/dumps/meertime_backup.sql:/docker-entrypoint-initdb.d/data.sql
  django:
    image: nexus.gwdc.org.au/meertime/django:3.0.0
    container_name: meertime_django
    depends_on:
      - postgres
    env_file:
      - backend/.env
    volumes:
      - ./src/static:/static
      - ./backend/media:/media
      - ~/meertime_docker_logs/django:/var/log/django
    command: >
      bash -c "python manage.py collectstatic --noinput
      && gunicorn --bind=0.0.0.0:8000 meertime.wsgi:application"
  react:
    image: nexus.gwdc.org.au/meertime/react:3.0.0
    container_name: meertime_react
    ports:
      - "3000:3000"
  nginx:
    image: nexus.gwdc.org.au/meertime/nginx:1.3
    ports:
      - "8000:80"
      - "80:80"
    container_name: meertime_nginx
    depends_on:
      - django
    volumes:
      - ./nginx:/etc/nginx/conf.d
volumes:
  mysql-persistent-storage:
