version: "3"

services:

  mysql:
    image: mysql:5.7.20
    container_name: meertime-mysql
    restart: unless-stopped
    volumes:
      - mysql-persistent-storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  django:
    build:
      context: .
      dockerfile: docker/meertime_django.Dockerfile
    container_name: meertime_django
    depends_on:
      - mysql
    volumes:
      - ./backend/static:/static
      - ./backend/media:/media
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - DB_HOST
      - MYSQL_PORT
      - DJANGO_SECRET_KEY
      - DEBUG
      - DEVELOPMENT_MODE
    command: >
      bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput
      && gunicorn --bind=0.0.0.0:8000 meertime.wsgi:application"

  react:
    build:
      dockerfile: ./docker/meertime_react.Dockerfile
      context: .
    container_name: react

  nginx:
    build:
      context: .
      dockerfile: docker/meertime_nginx.Dockerfile
    ports:
      - "8000:80"
    container_name: meertime_nginx
    depends_on:
      - django
      - react_app
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./backend/static:/static
      - ./backend/media:/media

volumes:
  mysql-persistent-storage:
