version: "3.8"

services:
  postgres:
    image: postgres:14.9
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  redis:
    image: redis
    restart: always
    command: redis-server --maxmemory-policy allkeys-lru --maxmemory 3GB
    ports:
      - "6379"

  django-service:
    build:
      context: .
      dockerfile: ./docker/meertime_django.Dockerfile
    restart: always
    volumes:
      - ./backend:/app
      - ./media:/media
      - /mnt/meertime_data:/mnt/meertime_data
    ports:
      - "8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  react-service:
    build:
      context: .
      dockerfile: ./docker/meertime_react.Dockerfile
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - "3000"

  nginx:
    build:
      context: .
      dockerfile: ./docker/meertime_nginx.Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./media:/media
    depends_on:
      - django-service
      - react-service
