version: '3'

services:
  mysql:
    image: mysql:5.7.20
    container_name: meertime-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: meertime
      MYSQL_USER: meertime
      MYSQL_PASSWORD: passwordgoeshere
    volumes:
      - mysql-persistent-storage:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: docker/meertime_django.Dockerfile
    container_name: meertime_django
    depends_on:
      - mysql
    volumes:
      - ./src/static:/static
    command: >
      ash -c "python manage.py collectstatic --noinput
      && gunicorn --bind=0.0.0.0:8000 meertime.wsgi:application"
  nginx:
    build:
      context: .
      dockerfile: docker/meertime_nginx.Dockerfile
    ports:
      - "32771:80"
    container_name: meertime_nginx
    depends_on:
      - web
    volumes:
      - ./src/nginx:/etc/nginx/conf.d
      - ./src/static:/static

volumes:
  mysql-persistent-storage:
