version: "3.8"

services:
  postgres:
    image: postgres:14.9
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - meertime_network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - meertime_network

  django-service:
    build:
      context: .
      dockerfile: ./docker/meertime_django.Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - meertime_network

  react-service:
    build:
      context: .
      dockerfile: ./docker/meertime_react.Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - meertime_network

  nginx:
    build:
      context: .
      dockerfile: ./docker/meertime_nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django-service
      - react-service
    networks:
      - meertime_network

volumes:
  postgres_data:

networks:
  meertime_network:
