version: "3"

services:
  mysql:
    image: mysql:5.7.20
    container_name: meertime-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
    volumes:
      - mysql-persistent-storage:/var/lib/mysql
  django:
    build:
      context: .
      dockerfile: docker/meertime_django.Dockerfile
    container_name: meertime_django
    depends_on:
      - mysql
    environment:
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST=mysql
      - DB_PORT
      - DJANGO_SECRET_KEY
      - DEBUG=False
    volumes:
      - ./src/static:/static
    command: >
      ash -c "python manage.py collectstatic --noinput
      && gunicorn --bind=0.0.0.0:8000 meertime.wsgi:application"
  nginx:
    build:
      context: .
      dockerfile: docker/meertime_nginx.Dockerfile
    ports:
      - "8000:80"
    container_name: meertime_nginx
    depends_on:
      - django
    volumes:
      - ./src/nginx:/etc/nginx/conf.d
      - ./src/static:/static
volumes:
  mysql-persistent-storage:
