# Generated by Django 3.2.19 on 2023-06-07 06:16

import dataportal.storage
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_cal_id', models.CharField(max_length=16)),
                ('calibration_type', models.CharField(choices=[('pre', 'pre'), ('post', 'post'), ('none', 'none')], max_length=4)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ephemeris',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ephemeris_data', models.JSONField(null=True)),
                ('ephemeris_hash', models.CharField(editable=False, max_length=32, null=True)),
                ('p0', models.FloatField()),
                ('dm', models.FloatField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('comment', models.TextField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(choices=[('UHF', 'UHF'), ('LBAND', 'LBAND'), ('SBAND_0', 'SBAND_0'), ('SBAND_1', 'SBAND_1'), ('SBAND_2', 'SBAND_2'), ('SBAND_3', 'SBAND_3'), ('SBAND_4', 'SBAND_4')], max_length=7)),
                ('frequency', models.FloatField()),
                ('bandwidth', models.FloatField()),
                ('nchan', models.IntegerField()),
                ('beam', models.IntegerField()),
                ('nant', models.IntegerField(blank=True, null=True)),
                ('nant_eff', models.IntegerField(blank=True, null=True)),
                ('npol', models.IntegerField()),
                ('obs_type', models.CharField(choices=[('fold', 'fold'), ('search', 'search')], max_length=6)),
                ('utc_start', models.DateTimeField()),
                ('raj', models.CharField(max_length=16)),
                ('decj', models.CharField(max_length=16)),
                ('duration', models.FloatField(null=True)),
                ('nbit', models.IntegerField()),
                ('tsamp', models.FloatField()),
                ('fold_nbin', models.IntegerField(blank=True, null=True)),
                ('fold_nchan', models.IntegerField(blank=True, null=True)),
                ('fold_nsub', models.IntegerField(blank=True, null=True)),
                ('filterbank_nbit', models.IntegerField(blank=True, null=True)),
                ('filterbank_npol', models.IntegerField(blank=True, null=True)),
                ('filterbank_nchan', models.IntegerField(blank=True, null=True)),
                ('filterbank_tsamp', models.FloatField(blank=True, null=True)),
                ('filterbank_dm', models.FloatField(blank=True, null=True)),
                ('ephemeris', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.ephemeris')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(max_length=64)),
                ('pipeline_description', models.CharField(blank=True, max_length=255, null=True)),
                ('pipeline_version', models.CharField(max_length=16)),
                ('pipeline_commit', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=64)),
                ('job_state', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('configuration', models.JSONField(blank=True, null=True)),
                ('ephemeris', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.ephemeris')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.observation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pulsar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('comment', models.TextField(help_text='Auto generated description based on information from the ANTF catalogue', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField()),
                ('bandwidth', models.FloatField()),
                ('nchan', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=255)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('template_type', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(null=True)),
                ('pulsar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.pulsar')),
            ],
        ),
        migrations.CreateModel(
            name='Toa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjd', models.CharField(blank=True, max_length=32, null=True)),
                ('uncertainty', models.FloatField(blank=True, null=True)),
                ('frequency', models.FloatField()),
                ('sn', models.FloatField()),
                ('nchan', models.IntegerField()),
                ('nsub', models.IntegerField()),
                ('site', models.CharField(blank=True, max_length=1, null=True)),
                ('quality', models.CharField(blank=True, choices=[('unassessed', 'unassessed'), ('good', 'good'), ('bad', 'bad')], max_length=10, null=True)),
                ('flags', models.JSONField()),
                ('ephemeris', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.ephemeris')),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.pipelinerun')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.template')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('calibration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.calibration')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('short', models.CharField(default='???', max_length=20)),
                ('embargo_period', models.DurationField(default=datetime.timedelta(days=548))),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('main_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.mainproject')),
            ],
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.template'),
        ),
        migrations.CreateModel(
            name='PipelineImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, storage=dataportal.storage.OverwriteStorage(), upload_to=dataportal.storage.get_upload_location)),
                ('image_type', models.CharField(blank=True, max_length=64, null=True)),
                ('cleaned', models.BooleanField(default=True)),
                ('resolution', models.CharField(choices=[('high', 'high'), ('low', 'low')], max_length=4)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.pipelinerun')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, storage=dataportal.storage.OverwriteStorage(), upload_to=dataportal.storage.get_pipeline_upload_location)),
                ('file_type', models.CharField(blank=True, max_length=32, null=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.pipelinerun')),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.project'),
        ),
        migrations.AddField(
            model_name='observation',
            name='pulsar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.pulsar'),
        ),
        migrations.AddField(
            model_name='observation',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.session'),
        ),
        migrations.AddField(
            model_name='observation',
            name='telescope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.telescope'),
        ),
        migrations.AddField(
            model_name='mainproject',
            name='telescope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.telescope'),
        ),
        migrations.CreateModel(
            name='FoldPulsarResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embargo_end_date', models.DateTimeField(null=True)),
                ('proposal', models.CharField(max_length=40)),
                ('dm', models.FloatField(null=True)),
                ('sn', models.FloatField(null=True)),
                ('flux', models.FloatField(null=True)),
                ('rm', models.FloatField(null=True)),
                ('ephemeris_download_link', models.URLField(null=True)),
                ('toas_download_link', models.URLField(null=True)),
                ('percent_rfi_zapped', models.FloatField()),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataportal.observation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataportal.project')),
                ('pulsar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.pulsar')),
            ],
        ),
        migrations.AddField(
            model_name='ephemeris',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.project'),
        ),
        migrations.AddField(
            model_name='ephemeris',
            name='pulsar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.pulsar'),
        ),
        migrations.AddConstraint(
            model_name='pipelineimage',
            constraint=models.UniqueConstraint(fields=('pipeline_run', 'image_type', 'cleaned', 'resolution'), name='unique image type for a processing'),
        ),
        migrations.AddConstraint(
            model_name='ephemeris',
            constraint=models.UniqueConstraint(fields=('project', 'ephemeris_hash'), name='Unique ephemeris for each project'),
        ),
    ]
