# Generated by Django 3.2.19 on 2023-06-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='fold_nsub',
            new_name='fold_tsubint',
        ),
    ]
