# Generated by Django 3.2.19 on 2023-07-26 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='calibration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='observations', to='dataportal.calibration'),
        ),
    ]
