# Generated by Django 3.2.19 on 2023-06-13 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0002_rename_fold_nsub_observation_fold_tsubint'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='phase_up_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='delay_cal_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='ephemeris',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='ephemeris',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2106, 2, 7, 6, 28, 15)),
        ),
    ]
