# Generated by Django 3.2.19 on 2023-06-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0003_auto_20230613_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='session',
        ),
        migrations.AddField(
            model_name='observation',
            name='calibration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.calibration'),
        ),
        migrations.AddField(
            model_name='pipelinefile',
            name='ozstar_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
