# Generated by Django 2.2.16 on 2020-10-12 07:26

import dataportal.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0003_auto_20200915_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='observations',
            name='bandpass',
            field=models.ImageField(null=True, storage=dataportal.storage.OverwriteStorage(), upload_to=dataportal.storage.get_upload_location),
        ),
        migrations.AddField(
            model_name='observations',
            name='phase_vs_frequency',
            field=models.ImageField(null=True, storage=dataportal.storage.OverwriteStorage(), upload_to=dataportal.storage.get_upload_location),
        ),
        migrations.AddField(
            model_name='observations',
            name='phase_vs_time',
            field=models.ImageField(null=True, storage=dataportal.storage.OverwriteStorage(), upload_to=dataportal.storage.get_upload_location),
        ),
        migrations.AddField(
            model_name='observations',
            name='profile',
            field=models.ImageField(null=True, storage=dataportal.storage.OverwriteStorage(), upload_to=dataportal.storage.get_upload_location),
        ),
        migrations.AddField(
            model_name='observations',
            name='snr_vs_time',
            field=models.ImageField(null=True, storage=dataportal.storage.OverwriteStorage(), upload_to=dataportal.storage.get_upload_location),
        ),
    ]
