# Generated by Django 3.2.19 on 2023-08-05 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0004_auto_20230804_0635"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calibration",
            options={"ordering": ["-start"]},
        ),
    ]
