# Generated by Django 2.2.16 on 2020-10-16 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0004_auto_20201012_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phaseup', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='fluxcal',
            name='nsubint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observations',
            name='nsubint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluxcal',
            name='phaseup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.PhaseUp'),
        ),
        migrations.AddField(
            model_name='fluxcal',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.Schedule'),
        ),
        migrations.AddField(
            model_name='observations',
            name='phaseup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.PhaseUp'),
        ),
        migrations.AddField(
            model_name='observations',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.Schedule'),
        ),
        migrations.AddField(
            model_name='searchmode',
            name='phaseup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.PhaseUp'),
        ),
        migrations.AddField(
            model_name='searchmode',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.Schedule'),
        ),
    ]
