# Generated by Django 3.2.19 on 2023-06-15 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0004_auto_20230613_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoldPulsarSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_observation', models.DateTimeField()),
                ('latest_observation', models.DateTimeField()),
                ('timespan', models.IntegerField()),
                ('number_of_observations', models.IntegerField()),
                ('total_integration_hours', models.FloatField()),
                ('last_integration_minutes', models.FloatField(null=True)),
                ('last_sn', models.FloatField()),
                ('highest_sn', models.FloatField()),
                ('lowest_sn', models.FloatField()),
                ('avg_sn_pipe', models.FloatField(null=True)),
                ('max_sn_pipe', models.FloatField(null=True)),
                ('main_project', models.CharField(max_length=64)),
                ('project', models.CharField(max_length=500)),
                ('all_projects', models.CharField(max_length=500)),
                ('pulsar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.pulsar')),
            ],
            options={
                'ordering': ['-latest_observation'],
                'unique_together': {('main_project', 'pulsar')},
            },
        ),
        migrations.CreateModel(
            name='Residual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjd', models.FloatField()),
                ('day_of_year', models.FloatField()),
                ('binary_orbital_phase', models.FloatField()),
                ('residual_sec', models.FloatField()),
                ('residual_sec_err', models.FloatField()),
                ('residual_phase', models.FloatField()),
                ('residual_phase_err', models.FloatField()),
                ('sn', models.FloatField()),
                ('frequency', models.FloatField()),
                ('nchan', models.IntegerField()),
                ('nsub', models.IntegerField()),
                ('site', models.CharField(blank=True, max_length=1, null=True)),
                ('quality', models.CharField(blank=True, choices=[('unassessed', 'unassessed'), ('good', 'good'), ('bad', 'bad')], max_length=10, null=True)),
                ('flags', models.JSONField()),
                ('ephemeris', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.ephemeris')),
            ],
        ),
        migrations.RemoveField(
            model_name='foldpulsarresult',
            name='dm',
        ),
        migrations.RemoveField(
            model_name='foldpulsarresult',
            name='ephemeris_download_link',
        ),
        migrations.RemoveField(
            model_name='foldpulsarresult',
            name='flux',
        ),
        migrations.RemoveField(
            model_name='foldpulsarresult',
            name='percent_rfi_zapped',
        ),
        migrations.RemoveField(
            model_name='foldpulsarresult',
            name='project',
        ),
        migrations.RemoveField(
            model_name='foldpulsarresult',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='foldpulsarresult',
            name='rm',
        ),
        migrations.RemoveField(
            model_name='foldpulsarresult',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='foldpulsarresult',
            name='toas_download_link',
        ),
        migrations.RemoveField(
            model_name='toa',
            name='uncertainty',
        ),
        migrations.AddField(
            model_name='foldpulsarresult',
            name='pipeline_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataportal.pipelinerun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='dm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='dm_chi2r',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='dm_epoch',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='dm_err',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='dm_tres',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='ephemeris_download_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='flux',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='percent_rfi_zapped',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='rm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='sn',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='toas_download_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='mjd_err',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_type',
            field=models.CharField(choices=[('cal', 'cal'), ('fold', 'fold'), ('search', 'search')], max_length=6),
        ),
        migrations.AlterField(
            model_name='toa',
            name='mjd',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PipelineImage',
        ),
        migrations.AddField(
            model_name='residual',
            name='pipeline_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.pipelinerun'),
        ),
        migrations.AddField(
            model_name='residual',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.template'),
        ),
    ]
