# Generated by Django 3.2.19 on 2023-06-16 04:53

import dataportal.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataportal', '0005_auto_20230615_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foldpulsarsummary',
            name='project',
        ),
        migrations.RemoveField(
            model_name='pipelinerun',
            name='pipeline_commit',
        ),
        migrations.RemoveField(
            model_name='template',
            name='bandwidth',
        ),
        migrations.RemoveField(
            model_name='template',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='template',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='template',
            name='location',
        ),
        migrations.RemoveField(
            model_name='template',
            name='method',
        ),
        migrations.RemoveField(
            model_name='template',
            name='nchan',
        ),
        migrations.RemoveField(
            model_name='template',
            name='template_type',
        ),
        migrations.AddField(
            model_name='template',
            name='band',
            field=models.CharField(choices=[('UHF', 'UHF'), ('LBAND', 'LBAND'), ('SBAND_0', 'SBAND_0'), ('SBAND_1', 'SBAND_1'), ('SBAND_2', 'SBAND_2'), ('SBAND_3', 'SBAND_3'), ('SBAND_4', 'SBAND_4')], default='LBAND', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='template_file',
            field=models.FileField(default=1, storage=dataportal.storage.OverwriteStorage(), upload_to=dataportal.storage.get_upload_location),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='template_hash',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ephemeris',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foldpulsarsummary',
            name='main_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.mainproject'),
        ),
        migrations.AlterField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('pulsar', 'project', 'band', 'template_hash'), name='Unique template for each pulsar, project and band.'),
        ),
    ]
