# Generated by Django 2.2.17 on 2021-09-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0006_auto_20210829_0722"),
    ]

    operations = [
        migrations.AddField(
            model_name="ephemerides",
            name="ephemeris_hash",
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
