# Generated by Django 3.2.19 on 2023-08-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0006_observationsummary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observationsummary",
            name="obs_type",
            field=models.CharField(
                choices=[("cal", "cal"), ("fold", "fold"), ("search", "search")], max_length=6, null=True
            ),
        ),
    ]
