# Generated by Django 3.2.19 on 2023-06-19 01:43

import dataportal.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0006_auto_20230616_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_file',
            field=models.FileField(null=True, storage=dataportal.storage.OverwriteStorage(), upload_to=dataportal.storage.get_upload_location),
        ),
    ]
