# Generated by Django 3.2.19 on 2023-08-14 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0007_alter_observationsummary_obs_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residual',
            name='toa',
        ),
        migrations.AddField(
            model_name='toa',
            name='residual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataportal.residual'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_hash',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
