# Generated by Django 3.2.19 on 2023-06-19 03:13

import dataportal.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0007_alter_template_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_file',
            field=models.FileField(null=True, storage=dataportal.storage.OverwriteStorage(), upload_to=dataportal.storage.get_template_upload_location),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
