# Generated by Django 3.2.19 on 2023-06-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0008_auto_20230619_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldpulsarsummary',
            name='most_common_project',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
