# Generated by Django 3.2.19 on 2023-08-23 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0008_auto_20230814_0214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PipelineFile',
        ),
    ]
