# Generated by Django 3.2.19 on 2023-06-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0009_auto_20230620_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='decj',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='observation',
            name='raj',
            field=models.CharField(max_length=32),
        ),
    ]
