# Generated by Django 3.2.19 on 2023-06-21 00:34

import dataportal.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0010_auto_20230621_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, storage=dataportal.storage.OverwriteStorage(), upload_to=dataportal.storage.get_upload_location)),
                ('cleaned', models.BooleanField(default=True)),
                ('image_type', models.CharField(choices=[('profile', 'profile'), ('profile-pol', 'profile-pol'), ('phase-time', 'phase-time'), ('phase-freq', 'phase-freq'), ('bandpass', 'bandpass'), ('snr-cumul', 'snr-cumul'), ('snr-single', 'snr-single')], max_length=16)),
                ('resolution', models.CharField(choices=[('high', 'high'), ('low', 'low')], max_length=4)),
                ('fold_pulsar_result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.foldpulsarresult')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pipelineimage',
            constraint=models.UniqueConstraint(fields=('fold_pulsar_result', 'image_type', 'cleaned', 'resolution'), name='Unique image type for a FoldPulsarResult'),
        ),
    ]
