# Generated by Django 3.2.19 on 2023-06-25 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0011_auto_20230621_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toa',
            old_name='frequency',
            new_name='freq_MHz',
        ),
        migrations.RemoveField(
            model_name='toa',
            name='flags',
        ),
        migrations.RemoveField(
            model_name='toa',
            name='nchan',
        ),
        migrations.RemoveField(
            model_name='toa',
            name='nsub',
        ),
        migrations.RemoveField(
            model_name='toa',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='toa',
            name='site',
        ),
        migrations.RemoveField(
            model_name='toa',
            name='sn',
        ),
        migrations.AddField(
            model_name='toa',
            name='archive',
            field=models.CharField(default='archive', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toa',
            name='be',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='bw',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='chan',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='f',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='fe',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='gof',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='nbin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='nch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='rcvr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='snr',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='subint',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='telescope',
            field=models.CharField(default='meerkat', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toa',
            name='tmplt',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='toa',
            name='tobs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='toa',
            name='ephemeris',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.ephemeris'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toa',
            name='mjd',
            field=models.DecimalField(decimal_places=12, max_digits=18),
        ),
    ]
