# Generated by Django 3.2.19 on 2023-10-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0012_auto_20230905_0418"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulsarfoldsummary",
            name="latest_observation_beam",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
