# Generated by Django 2.2.24 on 2021-09-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0012_auto_20210928_0220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ephemerides',
            unique_together={('pulsar', 'ephemeris_hash', 'dm', 'rm')},
        ),
    ]
