# Generated by Django 3.2.19 on 2023-06-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0012_auto_20230625_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldpulsarsummary',
            name='all_bands',
            field=models.CharField(default='LBAND', max_length=500),
            preserve_default=False,
        ),
    ]
