# Generated by Django 3.2.19 on 2023-06-30 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0013_foldpulsarsummary_all_bands'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineimage',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='pipelineimage',
            name='fold_pulsar_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='dataportal.foldpulsarresult'),
        ),
        migrations.AlterField(
            model_name='pipelineimage',
            name='image_type',
            field=models.CharField(choices=[('toa-single', 'toa-single'), ('profile', 'profile'), ('profile-pol', 'profile-pol'), ('phase-time', 'phase-time'), ('phase-freq', 'phase-freq'), ('bandpass', 'bandpass'), ('snr-cumul', 'snr-cumul'), ('snr-single', 'snr-single')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='job_state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=9),
        ),
    ]
