# Generated by Django 3.2.19 on 2023-07-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0014_auto_20230630_0722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoldPulsarSummary',
            new_name='PulsarFoldSummary',
        ),
    ]
