# Generated by Django 3.2.19 on 2023-07-03 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0015_rename_foldpulsarsummary_pulsarfoldsummary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoldPulsarResult',
            new_name='PulsarFoldResult',
        ),
        migrations.RemoveConstraint(
            model_name='pipelineimage',
            name='Unique image type for a FoldPulsarResult',
        ),
        migrations.RemoveField(
            model_name='pipelineimage',
            name='fold_pulsar_result',
        ),
    ]
