# Generated by Django 3.2.19 on 2023-11-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0016_auto_20231103_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulsarfoldresult',
            name='embargo_end_date',
        ),
        migrations.AddField(
            model_name='observation',
            name='embargo_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='band',
            field=models.CharField(choices=[('UHF', 'UHF'), ('LBAND', 'LBAND'), ('SBAND_0', 'SBAND_0'), ('SBAND_1', 'SBAND_1'), ('SBAND_2', 'SBAND_2'), ('SBAND_3', 'SBAND_3'), ('SBAND_4', 'SBAND_4'), ('OTHER', 'OTHER')], max_length=7),
        ),
        migrations.AlterField(
            model_name='observationsummary',
            name='band',
            field=models.CharField(choices=[('UHF', 'UHF'), ('LBAND', 'LBAND'), ('SBAND_0', 'SBAND_0'), ('SBAND_1', 'SBAND_1'), ('SBAND_2', 'SBAND_2'), ('SBAND_3', 'SBAND_3'), ('SBAND_4', 'SBAND_4'), ('OTHER', 'OTHER')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='band',
            field=models.CharField(choices=[('UHF', 'UHF'), ('LBAND', 'LBAND'), ('SBAND_0', 'SBAND_0'), ('SBAND_1', 'SBAND_1'), ('SBAND_2', 'SBAND_2'), ('SBAND_3', 'SBAND_3'), ('SBAND_4', 'SBAND_4'), ('OTHER', 'OTHER')], max_length=7),
        ),
    ]
