# Generated by Django 3.2.19 on 2023-07-03 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0016_auto_20230703_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineimage',
            name='pulsar_fold_result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='dataportal.pulsarfoldresult'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='pipelineimage',
            constraint=models.UniqueConstraint(fields=('pulsar_fold_result', 'image_type', 'cleaned', 'resolution'), name='Unique image type for a PulsarFoldResult'),
        ),
    ]
