# Generated by Django 3.2.19 on 2023-07-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0017_auto_20230703_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='rm_err',
            field=models.FloatField(null=True),
        ),
    ]
