# Generated by Django 3.2.19 on 2023-07-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0018_pipelinerun_rm_err'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineimage',
            name='image_type',
            field=models.CharField(choices=[('toa-dm-corrected', 'toa-dm-corrected'), ('toa-single', 'toa-single'), ('profile', 'profile'), ('profile-pol', 'profile-pol'), ('phase-time', 'phase-time'), ('phase-freq', 'phase-freq'), ('bandpass', 'bandpass'), ('snr-cumul', 'snr-cumul'), ('snr-single', 'snr-single')], max_length=16),
        ),
    ]
