# Generated by Django 3.2.19 on 2023-07-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0019_alter_pipelineimage_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='toa',
            name='dm_corrected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toa',
            name='maximum_nsubs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toa',
            name='minimum_nsubs',
            field=models.BooleanField(default=False),
        ),
    ]
