# Generated by Django 4.2.7 on 2023-11-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0019_remove_toa_unique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="toa",
            constraint=models.UniqueConstraint(
                fields=(
                    "observation",
                    "project",
                    "dm_corrected",
                    "obs_nchan",
                    "chan",
                    "minimum_nsubs",
                    "maximum_nsubs",
                    "subint",
                ),
                name="Unique ToA for observations, project and type of ToA (decimations).",
            ),
        ),
    ]
