# Generated by Django 4.2.7 on 2024-02-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0020_toa_unique_toa_for_observations_project_and_type_of_toa_decimations_"),
    ]

    operations = [
        migrations.AddField(
            model_name="toa",
            name="obs_npol",
            field=models.IntegerField(default=4),
        ),
    ]
