# Generated by Django 3.2.19 on 2023-07-06 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0021_toa_obs_nchan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residual',
            name='flags',
        ),
        migrations.RemoveField(
            model_name='residual',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='residual',
            name='nchan',
        ),
        migrations.RemoveField(
            model_name='residual',
            name='nsub',
        ),
        migrations.RemoveField(
            model_name='residual',
            name='pipeline_run',
        ),
        migrations.RemoveField(
            model_name='residual',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='residual',
            name='site',
        ),
        migrations.RemoveField(
            model_name='residual',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='residual',
            name='template',
        ),
        migrations.AddField(
            model_name='residual',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residual',
            name='pulsar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.pulsar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residual',
            name='toa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataportal.toa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residual',
            name='binary_orbital_phase',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='residual',
            name='ephemeris',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dataportal.ephemeris'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residual',
            name='residual_phase_err',
            field=models.FloatField(null=True),
        ),
    ]
