# Generated by Django 4.2.7 on 2024-02-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0022_remove_toa_unique_toa_for_observations_project_and_type_of_toa_decimations__and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toa",
            name="residual",
        ),
        migrations.AddField(
            model_name="toa",
            name="binary_orbital_phase",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="toa",
            name="day_of_year",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="toa",
            name="residual_phase",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="toa",
            name="residual_phase_err",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="toa",
            name="residual_sec",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="toa",
            name="residual_sec_err",
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Residual",
        ),
    ]
