# Generated by Django 3.2.19 on 2023-07-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0022_auto_20230706_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residual',
            name='mjd',
            field=models.DecimalField(decimal_places=12, max_digits=18),
        ),
    ]
