# Generated by Django 4.2.7 on 2024-02-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0024_alter_toa_day_of_year_alter_toa_residual_phase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelineimage",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("toa-single", "toa-single"),
                    ("profile", "profile"),
                    ("profile-pol", "profile-pol"),
                    ("phase-time", "phase-time"),
                    ("phase-freq", "phase-freq"),
                    ("bandpass", "bandpass"),
                    ("dynamic-spectrum", "dynamic-spectrum"),
                    ("snr-cumul", "snr-cumul"),
                    ("snr-single", "snr-single"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="toa",
            name="tmplt",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
