# Generated by Django 3.2.19 on 2023-07-10 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0025_auto_20230710_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residual',
            name='toa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residuals', to='dataportal.toa'),
        ),
        migrations.AlterField(
            model_name='toa',
            name='pipeline_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='toas', to='dataportal.pipelinerun'),
        ),
    ]
