# Generated by Django 4.2.7 on 2024-02-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0025_alter_pipelineimage_image_type_alter_toa_tmplt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="band",
            field=models.CharField(
                choices=[
                    ("UHF", "UHF"),
                    ("LBAND", "LBAND"),
                    ("SBAND_0", "SBAND_0"),
                    ("SBAND_1", "SBAND_1"),
                    ("SBAND_2", "SBAND_2"),
                    ("SBAND_3", "SBAND_3"),
                    ("SBAND_4", "SBAND_4"),
                    ("OTHER", "OTHER"),
                    ("UHF_NS", "UHF_NS"),
                ],
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="observationsummary",
            name="band",
            field=models.CharField(
                choices=[
                    ("UHF", "UHF"),
                    ("LBAND", "LBAND"),
                    ("SBAND_0", "SBAND_0"),
                    ("SBAND_1", "SBAND_1"),
                    ("SBAND_2", "SBAND_2"),
                    ("SBAND_3", "SBAND_3"),
                    ("SBAND_4", "SBAND_4"),
                    ("OTHER", "OTHER"),
                    ("UHF_NS", "UHF_NS"),
                ],
                max_length=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="band",
            field=models.CharField(
                choices=[
                    ("UHF", "UHF"),
                    ("LBAND", "LBAND"),
                    ("SBAND_0", "SBAND_0"),
                    ("SBAND_1", "SBAND_1"),
                    ("SBAND_2", "SBAND_2"),
                    ("SBAND_3", "SBAND_3"),
                    ("SBAND_4", "SBAND_4"),
                    ("OTHER", "OTHER"),
                    ("UHF_NS", "UHF_NS"),
                ],
                max_length=7,
            ),
        ),
    ]
