# Generated by Django 4.2.7 on 2024-04-17 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0028_pipelinerun_badges"),
        ("dataportal", "0028_remove_toa_unique_toa_for_observations_project_and_type_of_toa_decimations__and_more"),
    ]

    operations = []
