# Generated by Django 4.2.7 on 2024-04-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0032_remove_toa_unique_toa_for_observations_project_and_type_of_toa_decimations__and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toa",
            name="nsub_type",
            field=models.CharField(
                choices=[("1", "1"), ("max", "max"), ("all", "all"), ("mode", "mode")], max_length=4
            ),
        ),
    ]
