# Generated by Django 4.2.7 on 2025-01-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0033_alter_toa_nsub_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelineimage",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("toa-single", "toa-single"),
                    ("profile", "profile"),
                    ("profile-pol", "profile-pol"),
                    ("phase-time", "phase-time"),
                    ("phase-freq", "phase-freq"),
                    ("bandpass", "bandpass"),
                    ("dynamic-spectrum", "dynamic-spectrum"),
                    ("snr-cumul", "snr-cumul"),
                    ("snr-single", "snr-single"),
                    ("rmfit", "rmfit"),
                    ("dmfit", "dmfit"),
                ],
                max_length=16,
            ),
        ),
    ]
