# Generated by Django 4.2.21 on 2025-10-30 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dataportal", "0034_alter_pipelineimage_image_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMembershipRequest",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_requests",
                        to="dataportal.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_membership_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Membership Request",
                "verbose_name_plural": "Project Membership Requests",
                "indexes": [
                    models.Index(fields=["user", "project"], name="dataportal__user_id_69052e_idx"),
                    models.Index(fields=["project", "requested_at"], name="dataportal__project_15b50b_idx"),
                ],
                "unique_together": {("user", "project")},
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("Member", "Member"), ("Manager", "Manager"), ("Owner", "Owner")],
                        default="Member",
                        max_length=7,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this membership (null for initial owner)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="dataportal.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Membership",
                "verbose_name_plural": "Project Memberships",
                "indexes": [
                    models.Index(fields=["user", "project"], name="dataportal__user_id_0b2cd5_idx"),
                    models.Index(fields=["project", "role"], name="dataportal__project_273fa2_idx"),
                ],
                "unique_together": {("user", "project")},
            },
        ),
    ]
