# Generated by Django 4.2.21 on 2025-11-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0035_projectmembershiprequest_projectmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembershiprequest",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Approved", "Approved"), ("Rejected", "Rejected")],
                default="Pending",
                max_length=8,
            ),
        ),
    ]
