# Generated by Django 4.2.21 on 2025-11-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0036_projectmembershiprequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembership",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
