# Generated by Django 4.2.21 on 2025-12-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0037_projectmembership_is_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectmembershiprequest",
            unique_together=set(),
        ),
    ]
