# Generated by Django 4.2.21 on 2025-12-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0038_alter_projectmembershiprequest_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembershiprequest",
            name="rejection_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
