# Generated by Django 4.2.21 on 2026-01-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0039_add_rejection_note_to_projectmembershiprequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibration",
            name="badges",
            field=models.ManyToManyField(blank=True, to="dataportal.badge"),
        ),
        migrations.AlterField(
            model_name="observation",
            name="badges",
            field=models.ManyToManyField(blank=True, to="dataportal.badge"),
        ),
        migrations.AlterField(
            model_name="pipelinerun",
            name="badges",
            field=models.ManyToManyField(blank=True, to="dataportal.badge"),
        ),
    ]
