# Generated by Django 5.2.9 on 2026-01-06 01:08

import dataportal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0040_alter_calibration_badges_alter_observation_badges_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ephemeris",
            name="valid_from",
            field=models.DateTimeField(default=dataportal.models.default_ephemeris_start),
        ),
        migrations.AlterField(
            model_name="ephemeris",
            name="valid_to",
            field=models.DateTimeField(default=dataportal.models.default_ephemeris_end),
        ),
    ]
