# Generated by Django 4.2.21 on 2025-12-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0041_alter_ephemeris_valid_from_alter_ephemeris_valid_to"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ephemeris",
            index=models.Index(fields=["created_at"], name="dataportal__created_9b26c2_idx"),
        ),
        migrations.AddIndex(
            model_name="ephemeris",
            index=models.Index(fields=["pulsar", "created_at"], name="dataportal__pulsar__14a60f_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["utc_start"], name="dataportal__utc_sta_7aef1d_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["pulsar", "utc_start"], name="dataportal__pulsar__ead38b_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["project", "utc_start"], name="dataportal__project_d767ec_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["embargo_end_date"], name="dataportal__embargo_d78809_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(fields=["created_at"], name="dataportal__created_88cbbb_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(fields=["observation", "created_at"], name="dataportal__observa_be8da0_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(fields=["ephemeris"], name="dataportal__ephemer_a1e5eb_idx"),
        ),
    ]
