# Generated by Django 5.2.9 on 2026-01-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0041_alter_ephemeris_valid_from_alter_ephemeris_valid_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmembershiprequest",
            name="last_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of when the last reminder email was sent to project managers",
                null=True,
            ),
        ),
    ]
