# Generated by Django 5.2.9 on 2026-01-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0043_projectmembershiprequest_last_reminder_sent_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PipelineFile",
        ),
    ]
