# Generated by Django 5.2.9 on 2026-06-15 05:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0045_enforce_project_hierarchy"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="band_options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("UHF", "UHF"),
                        ("LBAND", "LBAND"),
                        ("SBAND_0", "SBAND_0"),
                        ("SBAND_1", "SBAND_1"),
                        ("SBAND_2", "SBAND_2"),
                        ("SBAND_3", "SBAND_3"),
                        ("SBAND_4", "SBAND_4"),
                        ("OTHER", "OTHER"),
                        ("UHF_NS", "UHF_NS"),
                    ],
                    max_length=7,
                ),
                blank=True,
                default=list,
                help_text="Supported observation bands to show for this project.",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="is_visible_on_frontend",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="plot_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Timing Residuals", "Timing Residuals"),
                        ("Flux Density", "Flux Density"),
                        ("S/N", "S/N"),
                        ("DM", "DM"),
                        ("RM", "RM"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                help_text="Supported plot types: DM, Flux Density, RM, S/N, Timing Residuals.",
                size=None,
            ),
        ),
    ]
