# Generated by Django 5.2.9 on 2026-06-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataportal", "0046_add_project_catalogue_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="allow_downloads",
            field=models.BooleanField(
                default=True, help_text="Allow users to download project data products."
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="observation_band_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UHF", "UHF"),
                    ("LBAND", "LBAND"),
                    ("SBAND_0", "SBAND_0"),
                    ("SBAND_1", "SBAND_1"),
                    ("SBAND_2", "SBAND_2"),
                    ("SBAND_3", "SBAND_3"),
                    ("SBAND_4", "SBAND_4"),
                    ("OTHER", "OTHER"),
                    ("UHF_NS", "UHF_NS"),
                ],
                default="",
                help_text="Override calculated observation bands for this project.",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="show_extended_observation_fields",
            field=models.BooleanField(
                default=True,
                help_text="Show extended observation fields in the public frontend.",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="toa_metadata_available",
            field=models.BooleanField(
                default=True,
                help_text="ToA files for this project include channel and receiver metadata.",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="use_for_folding_assets",
            field=models.BooleanField(
                default=True,
                help_text="Allow project ephemerides and templates to be selected as folding assets.",
            ),
        ),
    ]
