# Generated by Django 2.2.17 on 2021-08-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web_cache", "0002_auto_20210811_0642"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoldPulsarDetail",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("utc", models.DateTimeField(unique=True)),
                ("project", models.CharField(max_length=50)),
                ("length", models.DecimalField(decimal_places=1, max_digits=12)),
                ("beam", models.IntegerField()),
                ("bw_mhz", models.DecimalField(decimal_places=2, max_digits=12)),
                ("nchan", models.IntegerField()),
                (
                    "band",
                    models.CharField(
                        choices=[("L-BAND", "L-Band"), ("S-BAND", "S-Band"), ("UHF", "UHF"), ("UNKNOWN", "Unknown")],
                        max_length=6,
                    ),
                ),
                ("nbin", models.IntegerField()),
                ("nant", models.IntegerField()),
                ("nant_eff", models.IntegerField()),
                ("dm_fold", models.DecimalField(decimal_places=4, max_digits=12)),
                ("dm_meerpipe", models.DecimalField(decimal_places=2, max_digits=12)),
                ("rm_meerpipe", models.DecimalField(decimal_places=2, max_digits=12)),
                ("sn_backend", models.DecimalField(decimal_places=1, max_digits=12)),
                ("sn_meerpipe", models.DecimalField(decimal_places=1, max_digits=12)),
                (
                    "fold_pulsar",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web_cache.FoldPulsar"),
                ),
            ],
        ),
    ]
