# Generated by Django 2.2.17 on 2021-08-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0005_auto_20210816_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldpulsardetail',
            name='band',
            field=models.CharField(choices=[('L-BAND', 'L-Band'), ('S-BAND', 'S-Band'), ('UHF', 'UHF'), ('UNKNOWN', 'Unknown')], max_length=7),
        ),
    ]
