# Generated by Django 2.2.17 on 2021-08-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0006_auto_20210816_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldpulsardetail',
            name='utc',
            field=models.DateTimeField(),
        ),
    ]
