# Generated by Django 2.2.17 on 2021-08-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0010_auto_20210817_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldpulsardetail',
            name='frequency',
            field=models.DecimalField(decimal_places=9, max_digits=15, null=True),
        ),
    ]
