# Generated by Django 2.2.17 on 2021-08-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0011_foldpulsardetail_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldpulsar',
            name='beam',
            field=models.CharField(default='1', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchmodepulsar',
            name='beam',
            field=models.CharField(default='1', max_length=16),
            preserve_default=False,
        ),
    ]
