# Generated by Django 2.2.17 on 2021-08-23 02:07

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0012_auto_20210818_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldpulsardetail',
            name='emphemeris',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
