# Generated by Django 2.2.17 on 2021-08-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0013_foldpulsardetail_emphemeris'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foldpulsardetail',
            old_name='emphemeris',
            new_name='ephemeris',
        ),
    ]
