# Generated by Django 2.2.17 on 2021-08-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0015_foldpulsardetail_ephemeris_is_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldpulsar',
            name='band',
            field=models.CharField(choices=[('L-Band', 'L-Band'), ('S-Band', 'S-Band'), ('UHF', 'UHF'), ('UNKNOWN', 'Unknown')], max_length=7),
        ),
        migrations.AlterField(
            model_name='foldpulsardetail',
            name='band',
            field=models.CharField(choices=[('L-Band', 'L-Band'), ('S-Band', 'S-Band'), ('UHF', 'UHF'), ('UNKNOWN', 'Unknown')], max_length=7),
        ),
        migrations.AlterField(
            model_name='searchmodepulsar',
            name='band',
            field=models.CharField(choices=[('L-Band', 'L-Band'), ('S-Band', 'S-Band'), ('UHF', 'UHF'), ('UNKNOWN', 'Unknown')], max_length=7),
        ),
    ]
