# Generated by Django 2.2.17 on 2021-08-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0016_auto_20210830_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foldpulsardetail',
            old_name='nsubint',
            new_name='tsubint',
        ),
        migrations.AddField(
            model_name='foldpulsardetail',
            name='npol',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
