# Generated by Django 2.2.17 on 2021-10-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0021_auto_20211001_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionpulsar',
            old_name='intergrations',
            new_name='integrations',
        ),
    ]
