# Generated by Django 2.2.17 on 2021-10-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0022_auto_20211001_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionpulsar',
            name='beam',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
