# Generated by Django 2.2.17 on 2021-10-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0023_sessionpulsar_beam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionpulsar',
            name='integrations',
            field=models.FloatField(),
        ),
    ]
