# Generated by Django 2.2.17 on 2021-10-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0024_auto_20211011_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldpulsardetail',
            name='length',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='searchmodepulsardetail',
            name='length',
            field=models.FloatField(null=True),
        ),
    ]
