# Generated by Django 2.2.17 on 2021-11-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0034_auto_20211111_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionpulsar',
            name='session_display',
        ),
    ]
