# Generated by Django 2.2.17 on 2021-11-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_cache", "0038_auto_20211112_0055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessiondisplay",
            name="list_of_pulsars",
            field=models.TextField(null=True),
        ),
    ]
