# Generated by Django 2.2.17 on 2022-02-15 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_cache", "0044_auto_20220210_1106"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foldpulsardetail",
            name="frequency_hi",
        ),
    ]
