# Generated by Django 2.2.17 on 2022-02-15 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_cache", "0046_folddetailimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folddetailimage",
            name="process",
        ),
    ]
