# Generated by Django 2.2.17 on 2022-02-15 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_cache", "0047_remove_folddetailimage_process"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folddetailimage",
            name="name",
        ),
    ]
