# Generated by Django 2.2.17 on 2022-02-15 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web_cache", "0048_remove_folddetailimage_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folddetailimage",
            name="fold_pulsar_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="images", to="web_cache.FoldPulsarDetail"
            ),
        ),
    ]
