# Generated by Django 2.2.17 on 2022-05-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_cache", "0051_auto_20220223_0430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foldpulsar",
            name="band",
            field=models.CharField(
                choices=[("L-Band", "L-Band"), ("S-Band", "S-Band"), ("UHF", "UHF"), ("UNKNOWN", "Unknown")],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="searchmodepulsar",
            name="band",
            field=models.CharField(
                choices=[("L-Band", "L-Band"), ("S-Band", "S-Band"), ("UHF", "UHF"), ("UNKNOWN", "Unknown")],
                max_length=12,
            ),
        ),
    ]
