# Generated by Django 2.2.17 on 2022-05-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_cache", "0053_auto_20220505_0359"),
    ]

    operations = [
        migrations.AddField(
            model_name="foldpulsardetail",
            name="flux",
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
    ]
