# Generated by Django 2.2.17 on 2022-06-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0054_foldpulsardetail_flux'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldpulsar',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='searchmodepulsar',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
