# Generated by Django 2.2.17 on 2022-07-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0055_auto_20220614_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionpulsar',
            old_name='profile_hi',
            new_name='flux_hi',
        ),
        migrations.RenameField(
            model_name='sessionpulsar',
            old_name='profile_lo',
            new_name='flux_lo',
        ),
    ]
