# Generated by Django 2.2.17 on 2022-07-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_cache", "0056_auto_20220706_0107"),
        ("web_cache", "0052_auto_20220620_0323"),
    ]

    operations = []
