# Generated by Django 2.2.17 on 2022-11-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_cache", "0058_auto_20220803_0231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchmodepulsardetail",
            name="dm",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
