# Generated by Django 2.2.17 on 2022-12-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_cache", "0060_foldpulsardetail_ephemeris_download_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="foldpulsardetail",
            name="toas_download_link",
            field=models.URLField(null=True),
        ),
    ]
