# Generated by Django 2.2.17 on 2023-02-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_cache", "0061_foldpulsardetail_toas_download_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="foldpulsar",
            name="all_projects",
            field=models.CharField(default="FakeProject, AnotherONe", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="searchmodepulsar",
            name="all_projects",
            field=models.CharField(default="Fake Project", max_length=500),
            preserve_default=False,
        ),
    ]
