# Generated by Django 3.2.3 on 2023-02-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0063_auto_20230214_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldpulsardetail',
            name='ephemeris',
            field=models.JSONField(),
        ),
    ]
