# Generated by Django 3.2.3 on 2023-02-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_cache", "0064_alter_foldpulsardetail_ephemeris"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foldpulsardetail",
            name="ephemeris",
            field=models.JSONField(null=True),
        ),
    ]
