# Generated by Django 3.2.3 on 2023-05-03 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_cache", "0065_alter_foldpulsardetail_ephemeris"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="foldpulsar",
            unique_together={("main_project", "jname")},
        ),
        migrations.AlterUniqueTogether(
            name="searchmodepulsar",
            unique_together={("main_project", "jname")},
        ),
    ]
