# Generated by Django 3.2.19 on 2023-05-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0066_auto_20230503_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldpulsardetail',
            name='scrunched_download_link',
            field=models.URLField(null=True),
        ),
    ]
