# Generated by Django 3.2.19 on 2023-05-17 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0066_auto_20230503_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoldPulsarFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(max_length=64, null=True)),
                ('url', models.URLField()),
                ('fold_pulsar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web_cache.foldpulsar')),
            ],
        ),
    ]
