---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: db-bkp-cronjob
    app.kubernetes.io/instance: meertime
  name: db-bkp-cronjob
spec:
  schedule: 20 1 * * *
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 7
  jobTemplate:
    metadata:
      labels:
        app: db-bkp
        tier: database
        cronjob-name: db-bkp-job
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - /scripts/backup.sh
              env:
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: db-configmap
                      key: host
              envFrom:
                - secretRef:
                    name: db-control
                - secretRef:
                    name: db-config
              image: postgres:14.9
              imagePullPolicy: IfNotPresent
              name: postgres-backup-script
              resources: {}
              volumeMounts:
                - mountPath: /backup
                  name: backups
                - mountPath: /scripts
                  name: db-bkp-script
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
          volumes:
            - name: backups
              persistentVolumeClaim:
                claimName: db-storage-bkp-pvc-staging
            - configMap:
                name: db-bkp-script
              name: db-bkp-script
  successfulJobsHistoryLimit: 7
