---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-storage-bkp-pv-staging
  labels:
    app: db-bkp
    tier: database
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/sharedfolder/meertime-staging/bkp
    server: nfs1.private.loc
