apiVersion: v1
kind: Service
metadata:
  namespace: meertime
  name: django
spec:
  selector:
    app: dataportal
    tier: django
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: meertime
  name: django
  labels:
    app: dataportal
    tier: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataportal
      tier: django
  template:
    metadata:
      annotations:
        serviceAccountName: meertime
        vault.hashicorp.com/role: "meertime"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-retrieve-control.sh: "meertime/kv/nexus/service"
        vault.hashicorp.com/agent-inject-template-retrieve-control.sh: |
          {{- with secret "meertime/kv/nexus/service" -}}
          #!/bin/sh

          set -o nounset
          wget --no-check-certificate --http-user='{{ .Data.data.NEXUS_USER }}' --http-password='{{ .Data.data.NEXUS_PASS }}' {{ .Data.data.NEXUS_URL }}/{{ .Data.data.NEXUS_CONTROL_DIR }}/$1
          {{- end }}
      labels:
        app: dataportal
        tier: django
    spec:
      imagePullSecrets:
        - name: meertime-regcred
      hostAliases:
        - hostnames:
            - nexus.gw-cloud.org
          ip: 10.8.41.10
      serviceAccountName: meertime
      initContainers:
        - image: nexus.gw-cloud.org/docker/mysqldump:0.2
          name: mysql-control
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /mnt/mysql
            - name: mysql-control-script
              mountPath: /mnt/mysql-control
          command: ["/bin/sh", "/mnt/mysql-control/control-mysql.sh"]
        - name: migrate
          image: nexus.gw-cloud.org/meertime-dev/meertime_django:0.8
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          envFrom:
            - secretRef:
                name: django-multi
          command: ["python", "manage.py", "migrate"]
      containers:
        - name: django
          image: nexus.gw-cloud.org/meertime-dev/meertime_django:0.8
          resources: {}
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          envFrom: # defines DJANGO_SECRET_KEY and SENTRY_DSN
            - secretRef:
                name: django-multi
          command:
            ["gunicorn", "--bind=0.0.0.0:8000", "meertime.wsgi:application"]
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: mysql-control-script
          configMap:
            name: mysql-control-map
