apiVersion: v1
kind: Service
metadata:
  namespace: meertime
  name: django
spec:
  selector:
    app: dataportal
    tier: django
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: meertime
  name: django
  labels:
    app: dataportal
    tier: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataportal
      tier: django
  template:
    metadata:
      labels:
        app: dataportal
        tier: django
    spec:
      imagePullSecrets:
        - name: meertime-regcred
      serviceAccountName: meertime
      initContainers:
        - name: migrate
          image: nexus.gw-cloud.org/meertime-dev/meertime_django:0.3
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          command: ["python", "manage.py", "migrate"]
      containers:
        - name: django
          image: nexus.gw-cloud.org/meertime-dev/meertime_django:0.3
          resources: {}
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          command: ["gunicorn", "--bind=0.0.0.0:8000", "meertime.wsgi:application"]
