---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: meertime-img-storage-dev
  labels:
    app: dataportal
    tier: django
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/sharedfolder/meertime/img-dev
    server: nfs1.private.loc
