---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: meertime-img-storage
  labels:
    app: dataportal
    tier: django
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/sharedfolder/meertime/img
    server: 10.8.41.12

