---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: meertime-rolebinding
  labels:
    app: vault-agent
subjects:
  - kind: ServiceAccount
    name: meertime
roleRef:
  kind: Role
  name: meertime-role
  apiGroup: rbac.authorization.k8s.io
