---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-integrator-meertime
  namespace: meertime
  labels:
    app: vault-agent
spec:
  selector:
    matchLabels:
      app: vault-kube-integrator
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject-secret-regcred.yaml: "nexus/kv/docker"
        vault.hashicorp.com/agent-inject-template-regcred.yaml: |
          {{- with secret "nexus/kv/docker" -}}
          apiVersion: v1
          kind: Secret
          data:
            .dockerconfigjson: {{ .Data.data.auth }}
          metadata:
            namespace: meertime
            name: meertime-regcred
          type: kubernetes.io/dockerconfigjson
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-db-credentials.yaml: "meertime/kv/db"
        vault.hashicorp.com/agent-inject-template-db-credentials.yaml: |
          {{- with secret "meertime/kv/db" -}}
          apiVersion: v1
          kind: Secret
          type: Opaque
          data:
            {{ range $k, $v := .Data.data }}
            {{ $k }}: {{ $v }}
            {{ end }}
          metadata:
            namespace: meertime
            name: db-credentials
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-db-root-credentials.yaml: "meertime/kv/dbroot"
        vault.hashicorp.com/agent-inject-template-db-root-credentials.yaml: |
          {{- with secret "meertime/kv/dbroot" -}}
          apiVersion: v1
          kind: Secret
          type: Opaque
          data:
            password: {{ .Data.data.password }}
          metadata:
            namespace: meertime
            name: db-root-credentials
          {{- end }}
        vault.hashicorp.com/role: "meertime"
      labels:
        app: vault-kube-integrator
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 0
      serviceAccountName: meertime
      containers:
        - name: app
          image: bitnami/kubectl:1.17.4
          command: ["bash"]
          resources: {}
          livenessProbe:
            exec:
              command:
                - kubectl
                - apply
                - -f
                - /vault/secrets/
            initialDelaySeconds: 5
            periodSeconds: 5
          tty: true
