---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: meertime-storage-img-pv-staging
  labels:
    app: dataportal
    tier: django
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/sharedfolder/meertime-staging/img
    server: nfs1.private.loc
