---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: vault-agent
    app.kubernetes.io/instance: meertime
  name: secrets-integrator-meertime
  namespace: meertime-dev
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: vault-kube-integrator
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-init-first: "true"
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-pre-populate-only : "true"
            vault.hashicorp.com/agent-inject-secret-db-config-secret.yaml: kv/meertime/db-config
            vault.hashicorp.com/agent-inject-secret-db-control-secret.yaml: kv/meertime/db-control
            vault.hashicorp.com/agent-inject-secret-db-root-credentials.yaml: kv/meertime/dbroot
            vault.hashicorp.com/agent-inject-secret-django-multi-secret.yaml: kv/meertime/django-multi
            vault.hashicorp.com/agent-inject-secret-regcred.yaml: nexus/kv/docker
            vault.hashicorp.com/agent-inject-template-db-config-secret.yaml: |
              {{- with secret "kv/meertime/db-config" -}}
              apiVersion: v1
              kind: Secret
              type: Opaque
              data:
                {{ range $k, $v := .Data.data }}
                {{ $k }}: {{ $v }}
                {{ end }}
              metadata:
                namespace: meertime-dev
                name: db-config
              {{- end }}
            vault.hashicorp.com/agent-inject-template-db-control-secret.yaml: |
              {{- with secret "kv/meertime/db-control" -}}
              apiVersion: v1
              kind: Secret
              type: Opaque
              data:
                {{ range $k, $v := .Data.data }}
                {{ $k }}: {{ $v }}
                {{ end }}
              metadata:
                namespace: meertime-dev
                name: db-control
              {{- end }}
            vault.hashicorp.com/agent-inject-template-db-root-credentials.yaml:
              |
              {{- with secret "kv/meertime/dbroot" -}}
              apiVersion: v1
              kind: Secret
              type: Opaque
              data:
                password: {{ .Data.data.password }}
              metadata:
                namespace: meertime-dev
                name: db-root-credentials
              {{- end }}
            vault.hashicorp.com/agent-inject-template-django-multi-secret.yaml:
              |
              {{- with secret "kv/meertime/django-multi" -}}
              apiVersion: v1
              kind: Secret
              type: Opaque
              data:
                {{ range $k, $v := .Data.data }}
                {{ $k }}: {{ $v }}
                {{ end }}
              metadata:
                namespace: meertime-dev
                name: django-multi
              {{- end }}
            vault.hashicorp.com/agent-inject-template-regcred.yaml: |
              {{- with secret "nexus/kv/docker" -}}
              apiVersion: v1
              kind: Secret
              data:
                .dockerconfigjson: {{ .Data.data.auth }}
              metadata:
                namespace: meertime-dev
                name: meertime-regcred
              type: kubernetes.io/dockerconfigjson
              {{- end }}
            vault.hashicorp.com/role: meertime
        spec:
          containers:
            - name: meertime-vault-kube-integrator
              image: "bitnami/kubectl:1.17.4"
              imagePullPolicy: "IfNotPresent"
              command:
                - kubectl
                - apply
                - "-f"
                - /vault/secrets/
              resources: {}
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
          serviceAccountName: meertime
