# Source: grafana/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meertime-ingress
  labels:
    app: nginx
    app.kubernetes.io/instance: meertime
    tier: nginx
spec:
  rules:
    - host: dev.pulsars.org.au
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx-service
              port:
                number: 80
