apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-staging
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - image: postgres:14.9
          resources: {}
          name: mysql
          envFrom:
            - secretRef:
                name: db-config
          ports:
            - containerPort: 5432
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage-staging
              mountPath: /var/lib/postgresql/data
          # livenessProbe:
          #   exec:
          #     command:
          #       - psql
          #       - -w
          #       - -U
          #       - $POSTGRES_USER
          #       - -d
          #       - $POSTGRES_DATABASE
          #       - -c
          #       - "SELECT 1"
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          # readinessProbe:
          #   exec:
          #     # Check we can execute queries over TCP (skip-networking is off).
          #     command:
          #       - psql
          #       - -w
          #       - -U
          #       - $POSTGRES_USER
          #       - -d
          #       - $POSTGRES_DATABASE
          #       - -c
          #       - "SELECT 1"
          #   initialDelaySeconds: 5
          #   periodSeconds: 2
          #   timeoutSeconds: 1
      volumes:
        - name: mysql-persistent-storage-staging
          persistentVolumeClaim:
            claimName: mysql-pv-claim-staging
