---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage-bkp-pvc-staging
  labels:
    app: mysql-bkp
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: ""
