---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-bkp-storage-staging
  labels:
    app: mysql-bkp
    tier: database
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/sharedfolder/meertime-staging/db
    server: nfs1.private.loc
