---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: meertime-dev
  name: mysql-bkp-pv-claim-dev
  labels:
    app: mysql-bkp
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: ""
