---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage-dev
  labels:
    app: mysql
    tier: database
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/sharedfolder/meertime/mysql-dev
    server: nfs1.private.loc
