---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-bkp-storage
  labels:
    app: mysql-bkp
    tier: database
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/sharedfolder/meertime/mysqlbkp
    server: nfs1.private.loc
