---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  labels:
    app: mysql
    tier: database
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/sharedfolder/meertime/mysql
    server: 10.8.41.12
