apiVersion: v1
kind: Service
metadata:
  namespace: meertime
  name: nginx
  labels:
    app: nginx
    tier: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: dataportal
    tier: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: meertime
  name: ng-meertime
  labels:
    app: nginx
    tier: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataportal
      tier: nginx
  template:
    metadata:
      labels:
        app: dataportal
        tier: nginx
    spec:
      imagePullSecrets:
        - name: meertime-regcred
      serviceAccountName: meertime
      initContainers:
        - name: collectstatic
          image: nexus.gw-cloud.org/meertime-dev/meertime_django:0.6
          imagePullPolicy: Always
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: secret_key
          volumeMounts:
            - name: static-volume-django
              mountPath: /static
      containers:
        - name: ng-meertime
          image: nexus.gw-cloud.org/meertime-dev/meertime_nginx:0.4
          imagePullPolicy: Always
          resources: {}
          volumeMounts:
            - mountPath: /static
              name: static-volume-django
          livenessProbe:
            httpGet:
              path: /meertime
              port: 80
              httpHeaders:
            initialDelaySeconds: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /meertime
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: static-volume-django
          emptyDir: {}
