apiVersion: v1
kind: Service
metadata:
  namespace: meertime
  name: nginx
  labels:
    app: nginx
    tier: nginx
spec:
  ports:
    - port: 80
  selector:
    app: mysql
    tier: database
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: meertime
  name: ng-meertime
  labels:
    app: nginx
    tier: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataportal
      tier: nginx
  template:
    metadata:
      labels:
        app: dataportal
        tier: nginx
    spec:
      imagePullSecrets:
        - name: meertime-regcred
      serviceAccountName: meertime
      initContainers:
        - name: collectstatic
          image: nexus.gw-cloud.org/meertime-dev/meertime_django:0.4
          imagePullPolicy: Always
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: secret_key
          volumeMounts:
            - name: static-volume-django
              mountPath: /static
      containers:
        - name: ng-meertime
          image: nexus.gw-cloud.org/meertime-dev/meertime_nginx:0.3
          imagePullPolicy: Always
          resources: {}
          volumeMounts:
            - mountPath: /static
              name: static-volume-django
      volumes:
        - name: static-volume-django
          emptyDir: {}
