# Generated by Django 2.2.17 on 2022-04-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0002_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='status',
            field=models.CharField(choices=[('NOT_UPDATED', 'NOT_UPDATED'), ('UPDATED', 'UPDATED')], default='NOT_UPDATED', max_length=55),
        ),
    ]
