# Generated by Django 3.2.3 on 2023-02-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manage", "0005_update_users_for_flagged_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
    ]
