# Generated by Django 4.2.21 on 2025-05-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manage", "0007_apitoken"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="apitoken",
            constraint=models.UniqueConstraint(fields=("user", "name"), name="unique_token_name_per_user"),
        ),
    ]
