apiVersion: v1
kind: Service
metadata:
  namespace: meertime
  name: django
spec:
  selector:
    app: dataportal
    tier: django
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8000
  type: NodePort
  #type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: meertime
  name: django
  labels:
    app: dataportal
    tier: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataportal
      tier: django
  template:
    metadata:
      labels:
        app: dataportal
        tier: django
    spec:
      containers:
      - name: django
        image: testmt
        name: testmt
        imagePullPolicy: Never
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: host
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: name
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
        ports:
        - containerPort: 8080
