# Generated by Django 2.2.17 on 2021-08-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoldPulsar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_project', models.CharField(choices=[('MEERTIME', 'MeerTime'), ('TRAPUM', 'Trapum'), ('UNKNOWN', 'UNKNOWN')], max_length=8)),
                ('project', models.CharField(max_length=50)),
                ('band', models.CharField(choices=[('L-BAND', 'L-Band'), ('UHF', 'UHF')], max_length=6)),
                ('jname', models.CharField(max_length=64, unique=True)),
                ('latest_observation', models.DateTimeField()),
                ('first_observation', models.DateTimeField()),
                ('timespan', models.DurationField()),
                ('number_of_observations', models.IntegerField()),
                ('total_integration_hours', models.DecimalField(decimal_places=1, max_digits=12)),
                ('last_sn_raw', models.DecimalField(decimal_places=1, max_digits=12)),
                ('avg_sn_pipe', models.DecimalField(decimal_places=1, max_digits=12, null=True)),
                ('max_sn_pipe', models.DecimalField(decimal_places=1, max_digits=12, null=True)),
                ('last_integration_minutes', models.DecimalField(decimal_places=1, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchmodePulsar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_project', models.CharField(choices=[('MEERTIME', 'MeerTime'), ('TRAPUM', 'Trapum'), ('UNKNOWN', 'UNKNOWN')], max_length=8)),
                ('project', models.CharField(max_length=50)),
                ('band', models.CharField(choices=[('L-BAND', 'L-Band'), ('UHF', 'UHF')], max_length=6)),
                ('jname', models.CharField(max_length=64, unique=True)),
                ('latest_observation', models.DateTimeField()),
                ('first_observation', models.DateTimeField()),
                ('timespan', models.DurationField()),
                ('number_of_observations', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
