# Generated by Django 2.2.17 on 2021-08-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cache', '0008_searchmodepulsardetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodepulsardetail',
            name='nant_eff',
            field=models.IntegerField(null=True),
        ),
    ]
