#!/bin/bash
CHART_PATH="$1"
REMOTE_REPO="$2"
CHART_NAME="$3"
CHART_VERSION="$4"
NEXUS_CREDENTIALS="$5"
NEXUS_HELM_URL="$6"

# Extract major, minor, and patch versions from the local Chart.yaml
LOCAL_VERSION=$(awk '/^version:/ {print $2}' "$CHART_PATH/Chart.yaml" | awk '{ gsub(/"/, ""); print }')
IFS='.' read -r LOCAL_MAJOR LOCAL_MINOR LOCAL_PATCH <<< "$LOCAL_VERSION"

# Fetch the latest version from the remote repository
REMOTE_VERSION=$(helm search repo "$REMOTE_REPO/$CHART_NAME" | grep "$CHART_NAME" | awk '{print $2}')
echo "REMOTE_VERSION: $REMOTE_VERSION"
IFS='.' read -r REMOTE_MAJOR REMOTE_MINOR REMOTE_PATCH <<< "$REMOTE_VERSION"

# Compare versions
if ((LOCAL_MAJOR < REMOTE_MAJOR)) || ((LOCAL_MAJOR == REMOTE_MAJOR && LOCAL_MINOR < REMOTE_MINOR)) || ((LOCAL_MAJOR == REMOTE_MAJOR && LOCAL_MINOR == REMOTE_MINOR && LOCAL_PATCH < REMOTE_PATCH)); then
    echo "Error: Local chart version ($LOCAL_VERSION) is lower than the latest remote version ($REMOTE_VERSION)."
    exit 1
fi

if ((LOCAL_MAJOR > REMOTE_MAJOR)) || ((LOCAL_MAJOR == REMOTE_MAJOR && LOCAL_MINOR > REMOTE_MINOR)) || ((LOCAL_MAJOR == REMOTE_MAJOR && LOCAL_MINOR == REMOTE_MINOR && LOCAL_PATCH > REMOTE_PATCH)); then
    helm package $CHART_PATH
    curl -v -u $NEXUS_CREDENTIALS $NEXUS_HELM_URL/$CHART_NAME-${CHART_VERSION}.tgz --upload-file $CHART_NAME-${CHART_VERSION}.tgz
    helm search repo $REMOTE_REPO/$REMOTE_REPO
fi

if ((LOCAL_MAJOR == REMOTE_MAJOR && LOCAL_MINOR == REMOTE_MINOR && LOCAL_PATCH == REMOTE_PATCH)); then
    echo "Local version [$CHART_VERSION] is same as remote version."
    helm search repo $REMOTE_REPO/$REMOTE_REPO
fi

exit 0