#!/bin/bash

CHART_PATH="$1"
REMOTE_REPO="$2"
CHART_NAME="$3"

# Extract major, minor, and patch versions from the local Chart.yaml
LOCAL_VERSION=$(yq eval '.version' "$CHART_PATH/Chart.yaml")
IFS='.' read -r LOCAL_MAJOR LOCAL_MINOR LOCAL_PATCH <<< "$LOCAL_VERSION"

# Fetch the latest version from the remote repository
REMOTE_VERSION=$(helm search repo "$REMOTE_REPO/$CHART_NAME" | grep "$CHART_NAME" | awk '{print $2}')
echo "REMOTE_VERSION: $REMOTE_VERSION"
IFS='.' read -r REMOTE_MAJOR REMOTE_MINOR REMOTE_PATCH <<< "$REMOTE_VERSION"

# Compare versions
if ((LOCAL_MAJOR < REMOTE_MAJOR)) || ((LOCAL_MAJOR == REMOTE_MAJOR && LOCAL_MINOR < REMOTE_MINOR)) || ((LOCAL_MAJOR == REMOTE_MAJOR && LOCAL_MINOR == REMOTE_MINOR && LOCAL_PATCH < REMOTE_PATCH)); then
    echo "Error: Local chart version ($LOCAL_VERSION) is lower than the latest remote version ($REMOTE_VERSION)."
    exit 1
fi

exit 0