{{- range $key, $value := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace }}
data:
  host: {{ $value.host }}
---
{{- end }}