{{- range $key, $value := .Values.configMapScripts }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $value.label }}
data:
  {{ $value.scriptName }}: |-
{{ $value.script | indent 4 }}
---
{{- end }}