{{- range $key, $value := .Values.nfsStorage }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $value.name }}
  labels:
    {{- include "meertime-dataportal.labels" $ | nindent 4 }}
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ $value.path }}
    server: nfs1.private.loc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "meertime-dataportal.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: ""
  volumeName: {{ $value.name }}
---
{{- end }}