{{- range $key, $value := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name }}
  labels:
    {{- include "meertime-dataportal.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $value.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ $value.selector }}
---
{{- end }}
