{{- range $key, $value := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: {{ $value.label }}
spec:
  type: ClusterIP
  ports:
    - name: {{ $value.portName }}
      port: {{ $value.port }}
      targetPort: {{ $value.port }}
      protocol: TCP
  selector:
    name: {{ $value.selector }}
---
{{- end }}
